version: "3.4"

services:
  app:
    build: .
    working_dir: /usr/src/app
    command: 'bundle exec rails s'
    volumes:
      - .:/usr/src/app:cached
      - bundle-volume:/usr/src/app/vendor/bundle
      - node-volume:/usr/src/app/node_modules
      - /usr/src/app/tmp/pids/
    environment:
      - MY_NAME=fixme

  nginx:
    build: .
    command: 'nginx'
    ports:
      - '80:80'
    volumes:
      - .:/usr/src/app:cached
    environment:
      - TZ=Asia/Tokyo

volumes:
  node-volume:
  bundle-volume:
